name: Deploy Node + React to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install & Build React Client
        run: |
          cd client
          npm install
          npm run build

      - name: Install Server dependencies
        run: |
          cd server
          npm install

      - name: Copy React build to Server public folder
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Express Server to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fire-tracker-charlie'
          package: ./server
