name: Deploy FireTracker to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install & Build React (client)
        run: |
          cd client
          npm install
          npm run build

      - name: Install Express dependencies (server)
        run: |
          cd server
          npm install

      - name: Copy React build to Express public folder
        run: |
          rm -rf server/public
          mkdir -p server/public
          cp -r client/build/* server/public/

      - name: Deploy Express to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fire-tracker-charlie'
          package: ./server
